### ISSUE TITLE
Zoomify zoom key not working

### ISSUE THREAD

**Issue by thejekky** [moehreag/AxolotlClient-branding#111]
Hello, i tried out this mod today, and everything about it is great, the only problem is that Zoomify doesnt work with it, whenever i press the Zoomify zoom key nothing happens, this would be fine if my scroll wheel wasnt broken lol, zoomify lets me bind my zoom in/zoom out keys to a button, which i bound to my side mouse buttons, while in axolotl client i can only use my scroll wheel

When i disabled axolotl client, zoomify started working completely normally again, i tried out quilt loader version 0.21.0, 0.21.0-beta5 and 0.20.2, and nothing changed

Im using 1.20.1 on prism launcher

latest.log file https://mclo.gs/cSGdCgb

**Comment by thejekky** [comment]
Somehow in some way that confuses me, zoomify is now working fine with axolotl client, with none of the problems i had yesterday, all ive done (iirc) is add better ping display and chat heads back to my mod list, im just really confused rn lol

latest.log file https://mclo.gs/aD0Typa

**Comment by moehreag** [comment]
Unfortunately there is no info in the logs as to what went wrong for it to not work in the first place (because there probably just isn't anything that went wrong). Let's hope the issue doesn't randomly occur again which would make it quite hard to debug. I'll just say we'll consider adding keybinds for changing the zoom multiplier as well which would be another solution to your problem if the other approach cannot be worked out.

**Comment by thejekky** [comment]
forgot to write this earlier but, today i added 2 more mods to my mods folder (chatpatches and chatcalc) and the zoomify zoom key stopped working again, so it seems to be something related to the mod count? idk its a VERY weird bug, honestly just adding keybinds to the zoom multiplier would solve it
