### ISSUE TITLE
SLight issue with name.

### ISSUE THREAD

**Issue by Cuteistfox** [moehreag/AxolotlClient-branding#127]
This is not a "client" this is a client side utiltity mod with fetures. A client is more like platapus pvp(my clients thats just this with more performance and server specific mods). The modpack should be called axolotil client as it is a "client". The mod should be called axolotilmod or something.

**Comment by moehreag** [comment]
The name was chosen intentionally in order to attract users of so-called "clients" as they are the target audience of this mod (and organization, which actually bears the name). To be entirely honest, functionally wise none of those and neither this mod should be called clients in my opinion as they do not replace the entire minecraft client (but there are some projects that actually try re-implement it). You're probably referring to the name on the modrinth page, I do not see a need to change it though.
